specVersion: 0.0.4
description: Decentraland's Marketplace
repository: https://github.com/decentraland/decentraland
schema:
  file: ./schema.graphql
features:
  - ipfsOnEthereumContracts
dataSources:
  # ---------------------------------------------------------
  # ORDERS --------------------------------------------------
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: Marketplace
    network: mainnet
    source:
      address: '{{address:Marketplace}}'
      abi: Marketplace
      startBlock: {{startBlock:Marketplace}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/handlers/marketplace.ts
      entities:
        - Order
        - NFT
      abis:
        - name: Marketplace
          file: ./abis/Marketplace.json
      eventHandlers:
        - event: OrderCreated(bytes32,indexed uint256,indexed address,address,uint256,uint256,uint256)
          handler: handleOrderCreated
        - event: OrderSuccessful(bytes32,indexed uint256,indexed address,address,indexed address,uint256)
          handler: handleOrderSuccessful
        - event: OrderCancelled(bytes32,indexed uint256,indexed address,address,uint256)
          handler: handleOrderCancelled

  # ---------------------------------------------------------
  # BIDS ----------------------------------------------------
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: ERC721Bid
    network: mainnet
    source:
      address: '{{address:ERC721Bid}}'
      abi: ERC721Bid
      startBlock: {{startBlock:ERC721Bid}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/handlers/bid.ts
      entities:
        - Bid
      abis:
        - name: ERC721Bid
          file: ./abis/ERC721Bid.json
      eventHandlers:
        - event: BidCreated(bytes32,indexed address,indexed uint256,indexed address,uint256,uint256,bytes)
          handler: handleBidCreated
        - event: BidAccepted(bytes32,indexed address,indexed uint256,address,indexed address,uint256,uint256)
          handler: handleBidAccepted
        - event: BidCancelled(bytes32,indexed address,indexed uint256,indexed address)
          handler: handleBidCancelled
  # ---------------------------------------------------------
  # FUNDCHANNEL --------------------------------------------------
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: FundChannelUpgrades
    network: mainnet
    source:
      address: '{{address:FundChannelUpgrades}}'
      abi: FundChannelUpgrades
      startBlock: {{startBlock:FundChannelUpgrades}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/handlers/fundChannel.ts
      entities:
        - Order
        - NFT
      abis:
        - name: FundChannelUpgrades
          file: ./abis/FundChannelUpgrades.json
      eventHandlers:
        - event: AssertTypeAdded(indexed uint256,indexed address,indexed string)
          handler: handleAssertTypeAdded
        - event: AssertTypeUpdated(indexed uint256,indexed address,indexed string)
          handler: handleAssertTypeUpdated
          
# ---------------------------------------------------------
# TEMPLATES -----------------------------------------------
# ---------------------------------------------------------
templates:
  # ---------------------------------------------------------
  # ERC1155 -------------------------------------------------
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: ERC1155
    network: mainnet
    source:
      abi: ERC1155
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/handlers/erc1155.ts
      entities:
        - NFT
        - Parcel
        - Estate
        - Wearable
        - ENS
        - Props
      abis:
        - name: ERC1155
          file: ./abis/ERC1155.json
      eventHandlers:
        - event: TransferSingle(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleTransfer
        - event: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[])
          handler: handleTransfers
  - kind: ethereum/contract
    name: ERC721
    network: mainnet
    source:
      abi: ERC721
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/handlers/nft.ts
      entities:
        - NFT
        - Parcel
        - Estate
        - Wearable
        - ENS
        - NFTJSON
      abis:
        - name: ERC721
          file: ./abis/ERC721.json
        - name: LANDRegistry
          file: ./abis/LANDRegistry.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,indexed uint256,address,bytes,bytes)
          handler: handleTransfer
        - event: Transfer(indexed address,indexed address,indexed uint256,address,bytes)
          handler: handleTransfer
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: SetTokenURI(indexed uint256,indexed string,indexed string)
          handler: handleSetTokenURI
